### ISSUE TITLE
Error saving config, are all fields filled out?

### ISSUE THREAD

**Issue by kklemen** [ServerCentral/praeco#148]
When saving any rule (modifying existing or creating new) latest beta praeco always returns the error "Error saving config, are all fields filled out?"

Alert output channel does not matter. Will return the same error for any.

There is no output in console with debug and verbose turned on.

Saving rules with elastalert api (bypassing praeco) works okay.

Chmodded rules folder and all rule files with 777 just in case, no fix.

The only message in chrome console is "Unchecked runtime.lastError: The message port closed before a response was received." 

Thoughts?

**Comment by kklemen** [comment]
johnsusek, the hero we need. :)
Thank you very much. Great work. Love praeco.

Do you accept coffee tips?

**Comment by priamai** [comment]
Hi there,
I am experiencing this issue in Praeco version 1.51 with ES version 7.6.2.
It does seem to be related to something else from the logs:

```
07:18:51.182Z ERROR elastalert-server:
    TestController:  INFO:elastalert:Note: In debug mode, alerts will be logged to console but NOT actually sent.
                To send them but remain verbose, use --verbose instead.
    
    Traceback (most recent call last):
      File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/opt/elastalert/elastalert/test_rule.py", line 449, in <module>
        main()
      File "/opt/elastalert/elastalert/test_rule.py", line 445, in main
        test_instance.run_rule_test()
      File "/opt/elastalert/elastalert/test_rule.py", line 413, in run_rule_test
        rule_yaml = conf['rules_loader'].load_yaml(args.file)
      File "/opt/elastalert/elastalert/loaders.py", line 201, in load_yaml
        loaded = self.get_yaml(filename)
      File "/opt/elastalert/elastalert/loaders.py", line 530, in get_yaml
        return yaml_loader(filename)
      File "/home/node/.local/lib/python3.8/site-packages/staticconf/loader.py", line 167, in yaml_loader
        with open(filename) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/opt/elastalert/server_data/tests/../../rules/BaseRule.config'
```
And I didn't click the test button but just when I save.
The tests folder is empty:

```
bash-5.0$ ls -la /opt/elastalert/server_data/tests
total 12
drwxr-xr-x    1 node     node          4096 Jan  3 07:28 .
drwxr-xr-x    1 node     node          4096 Dec  7 15:23 ..
```
As well as the one is trying to load:

```
bash-5.0$ ls -la /opt/elastalert/server_data/tests/../../rules/
total 12
drwxr-xr-x    2 node     node          4096 Dec  7 15:23 .
drwxr-xr-x    1 node     node          4096 Jan  3 07:08 ..

```

Let me know if you need more info to find the culprit.
