### ISSUE TITLE
query log always shows No data

### ISSUE THREAD

**Issue by kklemen** [ServerCentral/praeco#150]
Praeco system interface for Query log always returns "No data". 
praeco v12

**Comment by kklemen** [comment]
7.1.1

Elasticsearch logs (possibly related?)

`[2019-08-26T18:30:22,347][DEBUG][o.e.a.s.TransportSearchAction] [elastic-175] All shards failed for phase: [query]
org.elasticsearch.index.query.QueryShardException: No mapping found for [alert_time] in order to sort on
        at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:319) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:153) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:772) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:608) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:583) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:386) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.search.SearchService.access$100(SearchService.java:124) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:358) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:354) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1069) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) ~[elasticsearch-7.1.1.jar:7.1.1]
`

**Comment by osherdp** [comment]
@johnsusek 
It seems like when creating an alert for the first time, which the default value of "is_enabled" is false . the Apscheduler can't enable it properly and causes the scheduler to print the following error:

"apscheduler.jobstores.base.JobLookError: 'No job by the id of test_rule was found'"

an easy fix for it would to have it enabled by default

**Comment by johnsusek** [comment]
Okay I'll probably make that change shortly, thanks for the report!

**Comment by osherdp** [comment]
@johnsusek that's great!
Of course, I'll try it tomorrow morning

**Comment by osherdp** [comment]
My problem was solved with the new version!
Thank you very much @johnsusek !!

**Comment by johnsusek** [comment]
you're welcome! closing issue
