### ISSUE TITLE
Receiving TypeError after saving rule

### ISSUE THREAD

**Issue by hgoscenski-vail** [ServerCentral/praeco#159]
After saving a rule and web ui indicating it saved correctly it never runs and the logs show that it is encountering a TypeError. The rule itself is pretty unexceptional and I will include it if you would like.

I am running praeco (v0.4.5) as a Docker container on Kubernetes.

```log
19:43:54.617Z ERROR elastalert-server:
    ProcessController:  /home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      InsecureRequestWarning)
    ERROR:apscheduler.executors.default:Job "ElastAlerter.handle_config_change (trigger: interval[0:02:00], next run at: 2019-09-04 19:45:54 UTC)" raised an exception
    Traceback (most recent call last):
      File "/home/node/.local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
        retval = job.func(*job.args, **job.kwargs)
      File "/opt/elastalert/elastalert/elastalert.py", line 1225, in handle_config_change
        self.load_rule_changes()
      File "/opt/elastalert/elastalert/elastalert.py", line 1059, in load_rule_changes
        new_rule_hashes = self.rules_loader.get_hashes(self.conf, self.args.rule)
      File "/opt/elastalert/elastalert/loaders.py", line 510, in get_hashes
        rule_mod_times[rule_file] = self.get_rule_file_hash(rule_file)
      File "/opt/elastalert/elastalert/loaders.py", line 537, in get_rule_file_hash
        rule_file_hash += self.get_rule_file_hash(import_rule_file)
    TypeError: can't concat str to bytes
```

**Comment by johnsusek** [comment]
Can you share your rule yaml?

**Comment by hgoscenski-vail** [comment]
I reinstalled on the cluster with the latest image tag from dockerhub so the rule name has changed but the error is the same.

```
16:04:07.499Z ERROR elastalert-server:
    ProcessController:  /home/node/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      InsecureRequestWarning)
    ERROR:apscheduler.executors.default:Job "ElastAlerter.handle_config_change (trigger: interval[0:02:00], next run at: 2019-10-23 16:06:07 UTC)" raised an exception
    Traceback (most recent call last):
      File "/home/node/.local/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
        retval = job.func(*job.args, **job.kwargs)
      File "/opt/elastalert/elastalert/elastalert.py", line 1225, in handle_config_change
        self.load_rule_changes()
      File "/opt/elastalert/elastalert/elastalert.py", line 1059, in load_rule_changes
        new_rule_hashes = self.rules_loader.get_hashes(self.conf, self.args.rule)
      File "/opt/elastalert/elastalert/loaders.py", line 510, in get_hashes
        rule_mod_times[rule_file] = self.get_rule_file_hash(rule_file)
      File "/opt/elastalert/elastalert/loaders.py", line 537, in get_rule_file_hash
        rule_file_hash += self.get_rule_file_hash(import_rule_file)
    TypeError: can't concat str to bytes
```

Here is the rule from the web interface:
```
__praeco_full_path: test2
__praeco_query_builder: '{"query":{"logicalOperator":"all","children":[]}}'
alert:
  - post
filter:
  - query:
      query_string:
        query: '@timestamp:*'
http_post_url: 'http://test:80'
import: BaseRule.config
index: kubernetes-hgoscenski*
is_enabled: true
name: test2
num_events: 501
realert:
  minutes: 5
terms_size: 50
timeframe:
  minutes: 10
timestamp_field: '@timestamp'
timestamp_type: iso
type: frequency
use_strftime_index: false
```

**Comment by nsano-rururu** [comment]
@hgoscenski-vail 

As a confirmation, did this always occur when saving the rules set on the screen? .. I've run into this problem from around 1.0.1 to the latest 1.8.4. Are you aware that this is a problem with a past version?

**Comment by nsano-rururu** [comment]
If you see TypeError: can't concat str to bytes, it's probably because the object you pass to data is unencoded.
It's a problem with elastalert, not praeco, elastalert-server.

Python 3.6 urllib TypeError: can't concat bytes to str
https://stackoverflow.com/questions/45037676/python-3-6-urllib-typeerror-cant-concat-bytes-to-str
