### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by tbhaxor** [ServerCentral/praeco#201]
After running the dev server, npm run serve

On browser console i am getting 

```
{
  "name": "praeco",
  "level": 50,
  "serverData": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Error: ENOENT: no such file or directory, open &#39;/opt/elastalert/config.yaml&#39;<br> &nbsp; &nbsp;at Object.openSync (fs.js:458:3)<br> &nbsp; &nbsp;at Object.readFileSync (fs.js:360:35)<br> &nbsp; &nbsp;at ConfigController._getConfig (/etc/elastalert-server/src/controllers/config/index.js:30:15)<br> &nbsp; &nbsp;at ConfigController.getConfig (/etc/elastalert-server/src/controllers/config/index.js:13:27)<br> &nbsp; &nbsp;at configGetHandler (/etc/elastalert-server/src/handlers/config/get.js:9:27)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/etc/elastalert-server/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/etc/elastalert-server/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/etc/elastalert-server/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/etc/elastalert-server/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /etc/elastalert-server/node_modules/express/lib/router/index.js:281:22</pre>\n</body>\n</html>\n",
  "levelName": "error",
  "msg": "",
  "time": "2020-04-25T13:52:51.802Z",
  "src": "webpack-internal:///./src/lib/networkError.js:140:69",
  "v": 1
```

The 500 Error is due to  http://localhost:8080/api/config

```
Error: ENOENT: no such file or directory, open '/opt/elastalert/config.yaml'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at ConfigController._getConfig (/etc/elastalert-server/src/controllers/config/index.js:30:15)
    at ConfigController.getConfig (/etc/elastalert-server/src/controllers/config/index.js:13:27)
    at configGetHandler (/etc/elastalert-server/src/handlers/config/get.js:9:27)
    at Layer.handle [as handle_request] (/etc/elastalert-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/etc/elastalert-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/etc/elastalert-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/etc/elastalert-server/node_modules/express/lib/router/layer.js:95:5)
    at /etc/elastalert-server/node_modules/express/lib/router/index.js:281:22
```

**Comment by tbhaxor** [comment]
Solved by copying `config.yaml` from elastalert directory to `/opt/elastalert/config.yaml`
